/*
-- Engineer: Miguel Angel Perez Polo
-- Create Date:	11/27/2014 
-- Project Name:	Practica 1 - Conversor ASCII to Code
 
*/


//_________ToCode___________

#define ToCode_A "41"
#define ToCode_B "42"
#define ToCode_C "43"
#define ToCode_D "44"
#define ToCode_E "45"
#define ToCode_F "46"
#define ToCode_G "47"
#define ToCode_H "48"
#define ToCode_I "49"
#define ToCode_J "4A"
#define ToCode_K "4B"
#define ToCode_L "4C"
#define ToCode_M "4D"
#define ToCode_N "4E"
#define ToCode_O "4F"
#define ToCode_P "50"
#define ToCode_Q "51"
#define ToCode_R "52"
#define ToCode_S "53"
#define ToCode_T "54"
#define ToCode_U "55"
#define ToCode_V "56"
#define ToCode_W "57"
#define ToCode_X "58"
#define ToCode_Y "59"
#define ToCode_Z "5A"
#define ToCode_CERO "30"
#define ToCode_UNO "31"
#define ToCode_DOS "32"
#define ToCode_TRES "33"
#define ToCode_CUATRO "34"
#define ToCode_CINCO "35"
#define ToCode_SEIS "36"
#define ToCode_SIETE "37"
#define ToCode_OCHO "38"
#define ToCode_NUEVE "39"
#define ToCode_INTERROGA "3F"
#define ToCode_COMA "2C"
#define ToCode_BLANCO "20"
#define ToCode_EXCLAMA "21"
#define ToCode_COMILLA "22"
#define ToCode_PUNTO "2E"

//_________ToASCII___________

#define ToASCII_A "A"
#define ToASCII_B "B"
#define ToASCII_C "C"
#define ToASCII_D "D"
#define ToASCII_E "E"
#define ToASCII_F "F"
#define ToASCII_G "G"
#define ToASCII_H "H"
#define ToASCII_I "I"
#define ToASCII_J "J"
#define ToASCII_K "K"
#define ToASCII_L "L"
#define ToASCII_M "M"
#define ToASCII_N "N"
#define ToASCII_O "O"
#define ToASCII_P "P"
#define ToASCII_Q "Q"
#define ToASCII_R "R"
#define ToASCII_S "S"
#define ToASCII_T "T"
#define ToASCII_U "U"
#define ToASCII_V "V"
#define ToASCII_W "W"
#define ToASCII_X "X"
#define ToASCII_Y "Y"
#define ToASCII_Z "Z"
#define ToASCII_CERO "0" 
#define ToASCII_UNO "1"
#define ToASCII_DOS "2"
#define ToASCII_TRES "3"
#define ToASCII_CUATRO "4"
#define ToASCII_CINCO "5"
#define ToASCII_SEIS "6"
#define ToASCII_SIETE "7"
#define ToASCII_OCHO "8"
#define ToASCII_NUEVE "9"
#define ToASCII_INTERROGA "?" 
#define ToASCII_COMA ","
#define ToASCII_BLANCO " "
#define ToASCII_EXCLAMA "!"
#define ToASCII_COMILLA "\""
#define ToASCII_PUNTO "."